# Generated by Django 2.1.15 on 2022-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment_content', models.CharField(max_length=500)),
                ('comment_author_name', models.CharField(max_length=255)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_link', models.CharField(max_length=150)),
                ('post_date', models.DateField()),
                ('post_upvotes', models.IntegerField()),
                ('post_author_name', models.CharField(max_length=255)),
            ],
        ),
    ]
