# Generated by Django 2.1.15 on 2022-01-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220114_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='comment_date',
            new_name='post_date',
        ),
    ]
